# Generated by Django 5.2.1 on 2025-05-23 04:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('letter', models.TextField()),
                ('video_filename', models.CharField(max_length=255)),
                ('preview_filename', models.CharField(max_length=255)),
                ('autor', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
